# Generated by Django 2.1.1 on 2018-10-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20181015_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='flightinfo',
            options={'managed': True},
        ),
    ]
