# Generated by Django 2.1.1 on 2018-10-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20181015_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdetails',
            name='price',
        ),
    ]
